### PR TITLE
Fix utilization graphs

### LINKED ISSUE #26: Flawed CPU usage displaying when cpu_interval differs.
When running two benchmarks with different cpu_interval values (other parameters are the same), the displayed cpu usage graph is wrong. On the attached image both benchmarks took 10 seconds, however, the base benchmark is shown to have taken only 6 seconds.

newplot (1)

Steps to reproduce:
```
defmodule SimpleScenario do
  @behaviour Beamchmark.Scenario

  @impl true
  def run() do
    1..1_000
    |> Stream.cycle()
    |> Stream.each(fn i -> Integer.pow(i, 2) end)
  end
end

Beamchmark.run(SimpleScenario,
  duration: 10,
  cpu_interval: 1500,
  formatters: [Beamchmark.Formatters.HTML]
)

Beamchmark.run(SimpleScenario,
  duration: 10,
  cpu_interval: 1000,
  formatters: [Beamchmark.Formatters.HTML]
)
```

### PR DESCRIPTION
**Pull request by roznawsk**

### CODE REVIEW

File: lib/beamchmark/suite/cpu/cpu_task.ex [hunk 1]
```diff
@@ -105,13 +105,14 @@ defmodule Beamchmark.Suite.CPU.CpuTask do
...
          cpu_usage: %{},
          average_all_cores: average_all_cores
        }}
     )
   end
 
-  @spec cpu_snapshot() :: CpuInfo.cpu_snapshot_t()
+  # @spec cpu_snapshot() :: CpuInfo.cpu_snapshot_t()
   defp cpu_snapshot() do
     cpu_util_result = :cpu_sup.util([:per_cpu])
```
Comment (DominikWolek) [inline lib/beamchmark/suite/cpu/cpu_task.ex]: Either delete the spec or provide valid type specifiation.

File: lib/beamchmark/formatters/html/templates.ex [hunk 2]
```diff
@@ -65,7 +65,7 @@ defmodule Beamchmark.Formatters.HTML.Templates do
         Enum.map_join(cpu_snapshots, ", ", fn %{cpu_usage: _cpu_usage, average_all_cores: avg} ->
           format_float(avg)
         end),
-      time: Enum.map_join(1..length(cpu_snapshots), ", ", fn el -> el end)
+      time: Enum.map_join(cpu_snapshots, ", ", fn snapshot -> snapshot.timestamp end)
```
Comment (DominikWolek) [inline lib/beamchmark/formatters/html/templates.ex]: NIT: ` Enum.map_join(cpu_snapshots, ", ", & &1.timestamp)` is much shorter (same for lines 96 and 110), but I leave the choice to you.

**Review by DominikWolek — APPROVED** [review]
